output_dir: 'experiments/outputs'
log_dir: 'experiments/log'
device: [0, 1]
#device: []
dataset:
  name: 'dogs'
  root: '/home/fischer/Desktop/Fischer/Projects/Unico_Challenge/dogs/train_organized'
  # num_workers: 16
  num_workers: 4
  split: False
  mean: [0.485, 0.456, 0.406]
  sigma: [0.229, 0.224, 0.225]
model:
  base: 'effNet' #['resnet18','resnet50','effNet']
  #freeze: False
  pretrained: True
  input_size: [224,224]
scheduler:
  type: None #[None,linear,exponential]
  step: 10
  decay: 0.94
train:
  # batch_size: 256
  batch_size: 16
  optimizer: 'SGD' #['adam','SGD', 'rmsprop']
  lr: 0.01
  num_epochs: 20
  loss_fn: 'CrossEntropy'
val:
  # batch_size: 256
  batch_size: 16
test:
  batch_size: 1
